# Generated by Django 5.0.2 on 2024-03-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacs',
            new_name='Contac',
        ),
    ]
